quotes = [
    "Start by doing what’s necessary; then do what’s possible; and suddenly you are doing the impossible. – Francis Of Assisi",
    "Start with good people, lay out the rules, communicate with your employees, motivate them and reward them. If you do all those things effectively, you can’t miss. – Lee Iacocca",
    "All things will be produced in superior quantity and quality, and with greater ease, when each man works at a single occupation, in accordance with his natural gifts, and at the right moment, without meddling with anything else. – Plato",
    "The way to get started is to quit talking and begin doing. – Walt Disney",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven’t found it yet, keep looking. Don’t settle. As with all matters of the heart, you’ll know when you find it. – Steve Jobs",
    "People often remark that I’m pretty lucky. Luck is only important in so far as getting the change to sell yourself at the right moment. After that, you’ve got to have talent and know how to use it. – Frank Sinatra",
    "Real integrity is doing the right thing, knowing that nobody’s going to know whether you did it or not. – Oprah Winfrey",
    "Infinite striving to be the best is man’s duty; It is its own reward. Everything else is in god’s hands.",
    "Its not that Im so smart, it’s just that I stay with problems longer. – Albert Einstein",
    "You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win. – Zig Ziglar",
    "Sometimes, things may not go your way, but the effort should be there every single night. – Michael Jordan",
    "Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy. – Norman Vincent Peale",
    "How poor are they that have not patience! What wound did ever heal but by degrees? – William Shakespeare",
    "The only thing to do with good advice is to pass it on. It is never of any use to oneself. – Oscar Wilde",
    "He who is not courageous enough to take risks will accomplish nothing in life. – Muhammad Ali",
    "Plans are nothing; planning is everything. – Dwight D. Eisenhower",
    "There are risks and costs to action. But they are far less than the long range risks of comfortable inaction. – John F. Kennedy",
    "If you’re going through hell, keep going. – Winston Churchill",
    "It is better to keep your mouth closed and let people think you are a fool than to open it and remove all doubt. – Mark Twain",
    "You can have everything in life you want, if you will just help other people get what they want. – Zig Ziglar",
    "Learning never exhausts the mind. – Leonardo da Vinci",
    "Good leadership consists of showing average people how to do the work of superior people. – John D. Rockefeller",
    "Our incomes are like our shoes; if too small, they gall and pinch us; but if too large, they cause us to stumble and to trip. – John Locke",
    "Love and work are the cornerstones of our humanness. – Sigmund Freud",
    "Rule No.1: Never lose money. Rule No.2: Never forget rule No.1. – Warren Buffett",
    "Obstacles are those frightful things you see when you take your eyes off your goal. – Henry Ford",
    "Gentleness doesn’t get work done unless you happen to be a hen laying eggs. – Coco Chanel",
    "Never neglect details. When everyone’s mind is dulled or distracted the leader must be doubly vigilant. – Colin Powell",
    "Advocates of capitalism are very apt to appeal to the sacred principles of liberty, which are embodied in one maxim: The fortunate must not be restrained in the exercise of tyranny over the unfortunate. – Bertrand Russell",
    "He who wishes to be rich in a day will be hanged in a year. – Leonardo da Vinci",
    "Remember that failure is an event, not a person. – Zig Ziglar",
    "Confidence… thrives on honesty, on honhonor, on the sacredness of obligations, on faithful protection and on unselfish performance. Without them it cannot live. – Franklin D. Roosevelt",
    "Discussion is an exchange of knowledge an argument an exchange of ignorance. – Robert Quillen",
    "Maintain your car, home, and other personal belongings you rely on.",
    "Luck is not chance, it’s toil; Fortune’s expensive smile is earned. – Emily Dickinson",
    "Work gives you meaning and purpose and life is empty without it. – Stephen Hawking",
    "Computers are useless. They can only give you answers. – Pablo Picasso",
    "The best minds are not in government. If any were, business would steal them away. – Ronald Reagan",
    "When you combine ignorance and leverage, you get some pretty interesting results. – Warren Buffett",
    "Tomorrow is the most important thing in life. Comes into us at midnight very clean. It’s perfect when it arrives and it puts itself in our hands. It hopes we’ve learned something from yesterday. – John Wayne",
]
